### ISSUE TITLE
Level 6 Platform

### ISSUE THREAD

**Issue by TNTftw21** [Royalkiller2222/royalkiller2222.github.io#1]
On Level 6, the platform second from the left in the middle is unreachable.

Also, 'sup, it's Charles.

**Comment by Royalkiller2222** [comment]
Ayyy lmao, I'll check it out.

**Comment by Royalkiller2222** [comment]
It is reachable, it is just there to force the player to learn that they can jump if they fall. Fall off while moving right, then jump the rest of the way.
