### ISSUE TITLE
Moved Repository

### ISSUE THREAD

**Issue by TNTftw21** [Royalkiller2222/royalkiller2222.github.io#2]
I forked this repository over to BreakMeso, since that's more where it belongs. You can play it from there at [this](breakmeso.github.io/platformer) address, although it won't have sound yet (I'll fix that when I have access to my laptop at home so that I can change everything using the git command on the terminal). You can delete everything out of this repository and build your own personal site here if you want.

**Comment by TNTftw21** [comment]
I should have mentioned, I plan on setting up BreakMeso's github website to use Jekyll, since that will make writing pages for it a lot easier. Since Jekyll uses templates to build everything with (and any "pages" build using Jekyll have to be a Markdown file), you should still be able to write HTML files without Jekyll screwing them up.

**Comment by Royalkiller2222** [comment]
Sounds good to me, I'll talk to you about it in Study Hall today.
